rvm:
    - 2.2.2

cache: bundler

before_script:
    - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz -O /tmp/tar_geckodriver.tar.gz;
    - tar -xzvf /tmp/tar_geckodriver.tar.gz
    - export PATH=$PATH:$PWD

addons:
    firefox: "49.0"
    code_climate:
        repo_token: 5b48a2bbbf03e9c87588768a9041958f465d83df080d1ad88384e363b5497b1b
